services: 

  reverse_proxy:
    image: nginxproxy/nginx-proxy
    container_name: revproxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # Exposed services
  gitea:
    image: gitea/gitea:1.18.5-rootless
    container_name: gitea
    volumes:
      - ${DIR}/gitea/data:/var/lib/gitea
      - ${DIR}/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=git.${DOMAIN}
      - VIRTUAL_PORT=3000
    restart: unless-stopped

  monica:
    image: monica:apache
    container_name: monica
    depends_on:
      - monica_db
    environment:
      - VIRTUAL_HOST=monica.${DOMAIN}
      - APP_ENV=
      - DB_HOST=monica_db
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD=secret
      - LOG_CHANNEL=stderr
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - QUEUE_DRIVER=sync
    volumes:
      - ${DIR}/monica/data:/var/www/html/storage
    restart: unless-stopped

  monica_db:
    image: mysql:8.0
    container_name: monica_db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - ${DIR}/monica/mysql:/var/lib/mysql
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - VIRTUAL_HOST=jellyfin.${DOMAIN}
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes: 
      - ${DIR}/jellyfin/config:/config
      - ${DIR}/jellyfin/tvshows:/data/tvshows
      - ${DIR}/jellyfin/movies:/data/movies
      - ${DIR}/jellyfin/music:/data/music
    restart: unless-stopped

  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - VIRTUAL_HOST=wiki.${DOMAIN}
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ${DIR}/dokuwiki/config:/config
    restart: unless-stopped
