services: 

  monica:
    image: monica
    depends_on:
      - monica_db
    ports:
      - 8080:80
    environment:
      - APP_KEY=base64:fx1eX/7e5GchUja6ctSF7h+wGXqLROlxrMm6mXDCyyk=
      - APP_DISABLE_SIGNUP=false # Necessário para criar uma conta inicial
      - DB_HOST=monica_db
      - DB_USERNAME=monica
      - DB_PASSWORD=secret
    volumes: 
      - data:/var/www/html/storage
    networks: 
      - master

  monica_db: 
    image: mysql:5.7
    environment: 
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    networks: 
      - master

volumes: 
  data: 
    name: data
  mysql: 
    name: mysql

networks:
  master: {}
