services: 

  reverse_proxy:
    image: nginxproxy/nginx-proxy
    container_name: revproxy
    ports:
      - 80:80 #optional
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # Exposed services
  gitea:
    image: gitea/gitea:1.18.5-rootless
    container_name: gitea
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=git.localhost
      - VIRTUAL_PORT=3000
    restart: unless-stopped

  monica:
    image: monica:apache
    container_name: monica
    depends_on:
      - monica_db
    environment:
      - VIRTUAL_HOST=monica.localhost
      - APP_ENV=
      - DB_HOST=monica_db
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD=secret
      - LOG_CHANNEL=stderr
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - QUEUE_DRIVER=sync
    volumes:
      - monica_data:/var/www/html/storage
    restart: unless-stopped

  monica_db:
    image: mysql:8.0
    container_name: monica_db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - monica_mysql:/var/lib/mysql
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - VIRTUAL_HOST=jellyfin.localhost
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes: 
      - jellyfin_config:/config
      - jellyfin_tvshows:/data/tvshows
      - jellyfin_movies:/data/movies
      - jellyfin_music:/data/music
    restart: unless-stopped

  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - VIRTUAL_HOST=wiki.localhost
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - dokuwiki_config:/config
    restart: unless-stopped

volumes: 
  jellyfin_config:
    name: jellyfin_config
  jellyfin_tvshows:
    name: jellyfin_tvshows
  jellyfin_movies:
    name: jellyfin_movies
  gitea-data:
    name: gitea-data
  gitea-config:
    name: gitea-config
  monica_data:
    name: monica_data
  monica_mysql:
    name: monica_mysql
